Add Ofsted Market Analysis tool
data-to-insight/patch pull request #13
Opened 2023-06-16 13:47 UTC by Paggers92

Add Ofsted Market Analysis tool

2023-06-16 13:48 UTC, WillLP-code requested changes
I'd like this to have a title and description

2023-06-20 12:38 UTC, WillLP-code reviewed
Hi Simon, this is great, I'll get this so it can go live now!

2023-06-20 12:43 UTC, Paggers92 commented
Thanks!

Could you send me the link so I can access the app? Or can I access it from the PATCh github?

Simon

***@***.***<https://www.hertfordshire.gov.uk/home.aspx>
Simon Pagden
Community Intelligence & Data Science Team | Improvement & Technology | Resources
Hertfordshire County Council
County Hall, Pegs Lane, Hertford, SG13 8DE, Postal Point: CHN305
T: 01992 556926 (Internal: 56926)
E: ***@***.******@***.***>
[Hertfordshire County Council Facebook]<https://www.facebook.com/hertscountycouncil/>[Hertfordshire County Council Twitter]<http://www.twitter.com/hertscc>[Hertfordshire County Council email updates]<https://www.hertfordshire.gov.uk/statweb/webteam/updateme/>

***@***.***<https://hertscc365.sharepoint.com/sites/intranet/Services/Resources/Intelligence>

For information about Hertfordshire and its local communities, go to Herts Insight<https://beta.hertfordshire.gov.uk/microsites/herts-insight/home.aspx>
Follow Herts Insight on twitter<https://twitter.com/HertsInsight>


From: William Levack Payne ***@***.***>
Sent: 20 June 2023 13:39
To: data-to-insight/patch ***@***.***>
Cc: Simon Pagden ***@***.***>; Author ***@***.***>
Subject: Re: [data-to-insight/patch] Add Ofsted Market Analysis tool (PR #13)


@WillLP-code commented on this pull request.

Hi Simon, this is great, I'll get this so it can go live now!

—
Reply to this email directly, view it on GitHub<https://github.com/data-to-insight/patch/pull/13#pullrequestreview-1488055843>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6TPLW74ZJA742PFVOQL2STXMGKUZANCNFSM6AAAAAAZJJE3UI>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

****Disclaimer****
The information in this message should be regarded as confidential and is intended for the addressee only unless explicitly stated.  If you have received this message in error it must be deleted and the sender notified.  The views expressed in this message are personal and not necessarily those of Hertfordshire County Council unless explicitly stated. Please be aware that emails sent to or received from Hertfordshire County Council may be intercepted and read by the council.  Interception will only occur to ensure compliance with council policies or procedures or regulatory obligations, to prevent or deter crime, or for the purposes of essential maintenance or support of the email system.

2023-06-20 12:45 UTC, WillLP-code approved these changes

2023-06-20 12:45 UTC, merged